<<<<<<< HEAD
baseurl = "https://ctenofive.github.io"
googleAnalytics = ""
>>>>>>> 08bd46fc4feffb644d6b59c1a19715b5c532ed21
languageCode = "en-us"
paginate = 10
theme = "hugo-minimalist-theme"
title = "Thoughts by __"
[params]
avatar = "img/profile-image.png"
copyright = "Powered by [Hugo](http://gohugo.io)."
custom_css = []
custom_js = []
google_analytics = ""
header_background = "img/desk.jpg"
header_title = "Thoughts by __"
location = "Earth"
site_author = "Ctenofive"
site_description = "Thoughts by [insert here]"
[social]
behance = ""
dribbble = ""
facebook = ""
github = "ctenofive"
gplus = ""
instagram = ""
linkedin = ""
twitter = ""
